### ISSUE TITLE
Disconnects after an input

### ISSUE THREAD

**Issue by NotANullPointer** [jakibaki/sys-netcheat#1]
Hi! I'm having a problem with your module,
after sending one command, netcat immediately disconnects from my switch.
You can see it in the screenshot I've attached.
![image](https://user-images.githubusercontent.com/13029101/43167412-da9cb4ca-8f99-11e8-9204-fbc1e16aeee1.png)

**Comment by jakibaki** [comment]
Oh, that's certainly not what I'm experiencing D:

Are you completely sure that you have `fullsvcperm=1` and `debugmode=1` in the right place of your hekate ini?

**Comment by NotANullPointer** [comment]
I was using them, I'm pretty sure

**Comment by NotANullPointer** [comment]
Just tried again and doesn't work, I'm 100% sure I set those

**Comment by jakibaki** [comment]
:/ What firmware are you on?

**Comment by NotANullPointer** [comment]
5.1.0, the latest

**Comment by jakibaki** [comment]
Could you please try with another game open?

**Comment by NotANullPointer** [comment]
Tried with Kirby Star Allies now, and still the same

**Comment by jakibaki** [comment]
:(

Try updating to the latest version if you aren't on it already but other then that I'm unfortunately out of ideas.

**Comment by NotANullPointer** [comment]
Still crashes with latest

**Comment by NotANullPointer** [comment]
Here you are
[hekate_ipl.ini](https://github.com/jakibaki/sys-netcheat/files/2227716/hekate_ipl.txt)

**Comment by jakibaki** [comment]
> I'm 100% sure I set those

They aren't set in this config...

```
[config]
autoboot=2
bootwait=5
customlogo=0
verification=2
[Stock]
[CFW]
kip1=modules/sm.kip1
kip1=modules/sys-netcheat.kip
kip1=modules/nx-dreport.kip
fullsvcperm=1
debugmode=1
```

Here's the fixed config.

**Comment by NotANullPointer** [comment]
hm, maybe i forgot to save it

**Comment by NotANullPointer** [comment]
Tho in the older ones they were under [config]
maybe that was the problem

**Comment by jakibaki** [comment]
Yeah, they're supposed to be in the entry so you can configure them according to your needs (wouldn't want to start the switch with debugging enabled if you're booting stock).

**Comment by NotANullPointer** [comment]
Works perfectly now, you may want to specify in the readme about this tho
