### ISSUE TITLE
NetCat cmd closes after input

### ISSUE THREAD

**Issue by Glitchybun** [jakibaki/sys-netcheat#13]
I saw a post in the Issues-section regarding this problem but the solution provided, didnt work for me.
everytime i want to connect it some text pops up in the cmd for a split second and then it closes the CMD.
I have almost no experience in cmd stuff btw.

I modified the file (adding the few lines in "hekate_ipl.ini") and moved the other file to modules,
then started netcat 1.12 and my switch with CFW, Opened Botw and startet typing: 
"nc [The Switch IP] 5555"
that didnt work so i tried these afterwards:
"nc [The Switch IP] 5000"
"nc64 [The Switch IP] 5555"
"[The Switch IP] 5555"
"[The Switch IP] 5000"
Then i tried restarting... Checked my Internet status...

Heres some stuff that meight be the cause of this:
I have the Latest Firmware on the switch itself (v5.1.0)
I added some DNS stuff to my Internet conection (was recommended so Nintendo doesnt notice (?))
Some homebrew stuff i have installed like SDFilesUpdater
And the ftpd-app doesnt work for me either (everytime i connect it, itdoesnt show the contents of the sd)

Would appreciate some help. Thanks in advance!

**Comment by jakibaki** [comment]
* Open the nc-folder with the windows explorer
* Click on the bar where your current path is listed
* enter `cmd` then press return
A command line windows should now pop up prompting you to enter a command.  
* enter `nc64 [The Switch IP] 5555`
* The netcheat-prompt should now appear. If it doesn't at least you should now be able to see the error which you can use for further debugging.

**Comment by Glitchybun** [comment]
It doesnt close automatically anymore but it doesnt display an error either...
I tried some different variations aswell

![cmd](https://user-images.githubusercontent.com/42678208/44616759-e441bc80-a855-11e8-96cb-71835abf4d5b.PNG)

**Comment by jakibaki** [comment]
It looks like netcheat isn't configured properly on your switch. Please make sure that it's connected to the same network as your computer and that you're entering the correct ip.

If that still doesn't work make sure that you're using the correct profile (the one in the sdfiles is broken right now so you'll have to add the 
```
debugmode=1
fullsvcperm=1
```
flags manually if you're using that.

If that still doesn't work please try again with 

`nc64 -v SWITCH_IP 5555`

**Comment by Glitchybun** [comment]
ok, it works now! 
Tho, i noticed that the hekate_ipl file apparently reset itself somehow... the few lines of code i added before were not there anymore.
anyway, thanks for all the help and explaining.
