### ISSUE TITLE
Host not found.

### ISSUE THREAD

**Issue by 98otiss03** [jakibaki/sys-netcheat#2]
![image](https://user-images.githubusercontent.com/38541316/43182404-abd3f9a0-8fb7-11e8-8672-11397498b886.png)
everytime i use this it never connects, i do have debug and fullsvcperm in the ipl.
both devices, pc and switch are connected to the same wifi.
if i double click on nc and type the command it closes
if i run it through cmd/powershell it says host not found.

**Comment by jakibaki** [comment]
Could you please try if another web-connected app works for you (for example ftpd)?

**Comment by 98otiss03** [comment]
sysftpd and ftpd work perfectly.

**Comment by jakibaki** [comment]
oh, I see it. You're entering the command wrong. This is how you're supposed to do it:

`nx64.exe YOUR_SWITCH_IP 5555`

**Comment by 98otiss03** [comment]
theres no nx64.exe

**Comment by jakibaki** [comment]
oh, i meant `nc64.exe` instead of `nx64.exe`

**Comment by Tenshi68** [comment]
do you succeed on switch???
