### ISSUE TITLE
Stuck on Switch splash screen 

### ISSUE THREAD

**Issue by lborruto** [jakibaki/sys-netcheat#27]
Issue: 
When launching Atmosphere through Hekate with the CFW + sys-netcheat configuration, it boots then freezes on the logo splash screen (Kosmos pack).

Inject Hekate payload
Choose to boot the CFW + sys-netcheat config
Wait for Switch logo splash screen
See error
Freeze on Switch logo when booting

Version :
Release Version Kosmos : 11.7
Option : Atmosphere w/Hekate 4.6
Firmware : 6.2

**Comment by hernan43** [comment]
I have this exact same issue,

**Comment by Temmie45** [comment]
Just tried this myself and had this happen. Had the same version for everything

**Comment by AgentTechnoman** [comment]
+1 for same behavior here.

**Comment by jakibaki** [comment]
Fixed in 1.3.4 :)

**Comment by hernan43** [comment]
Thank you for your hard work!
