### ISSUE TITLE
Crashes Switch right after the Switch logo fades away 

### ISSUE THREAD

**Issue by Sn0wbody** [jakibaki/sys-netcheat#28]
Using ReiNX 2.0 update, Sys-netcheat now crashes my switch every time i launch it, right after the switch logo fades away.

**Comment by jakibaki** [comment]
Current atmos/6.2 compatibility has been fixed with the new 1.3.4 release.

No clue about reinx though but it's not officially supported

**Comment by Sn0wbody** [comment]
The latest update now works with ReiNX 2
Thank you very much ♥
