### ISSUE TITLE
(UNKNOWN) [Switch_IP] 5555 (?) : Connection refused

### ISSUE THREAD

**Issue by ghost** [jakibaki/sys-netcheat#31]
in the title

**Comment by RubberDuck55** [comment]
title

**Comment by kenji4861** [comment]
Probably a firewall setting on your own computer or your router. Do you have any special software running on your computer?

**Comment by Tenshi68** [comment]
Launch by hekate

**Comment by ghost** [comment]
needed more hekate stuff
