### ISSUE TITLE
Unable to change memory value on version 6.20

### ISSUE THREAD

**Issue by kenji4861** [jakibaki/sys-netcheat#32]
Trying to change the rupees on Hyrule Warriors.
I can search the value, but poking or freezing the value on 6.2 doesn't seem to do anything.

In this example, I have 101873 rupees

> ssearch u32 101873
Got a hit at 7bd188a564!
Got a hit at 7bdcc0d9fc!

> afreeze 7bd188a564 u32 987654
> afreeze 7bdcc0d9fc u32 987654

> lfreeze
0) 7bd188a564 (u32) = 987654
1) 7bdcc0d9fc (u32) = 987654

> ssearch u32 101873
Got a hit at 7bd188a564!
Got a hit at 7bdcc0d9fc!

> ssearch u32 987654
> 

Even after freezing the rupees to 987654, it stays at 101873

**Comment by timleeuchees** [comment]
I have the same issue previously. After adding below settings in hekate_pl.ini, it works.
```
fullsvcperm=1
debugmode=1
kip1patch=nosigchk
```

**Comment by kenji4861** [comment]
Thank you timleeuchees!!!! That solved it!

fullsvcperm=1 | Disables SVC verification (full services permission)
debugmode=1 | Enables Debug mode

Also here's the output to show that it worked!
> ssearch u32 203725
Got a hit at 6c98241138!
Got a hit at 6c9828a564!
Got a hit at 6c982bd334!
Got a hit at 6c9856cd80!
Got a hit at 6c9b347e6c!
> csearch 204725
Got a hit at 6c9828a564!
Got a hit at 6c9b347e6c!
> poke 6c9828a564 u32 987654
> poke 6c9b347e6c u32 987654
> ssearch u32 987654
Got a hit at 6c9828a564!
Got a hit at 6c9b347e6c!

woohoo!!!! Thank you!
