### ISSUE TITLE
[Suggestion] Recompile as PM Module

### ISSUE THREAD

**Issue by EphraimBane** [jakibaki/sys-netcheat#33]
Atmosphere makes loading kips annoying. I think we should use PM modules, since SciresM has specifically stated that he'd like people to migrate to them.

**Comment by jakibaki** [comment]
Already happened. Will be included in the next release (which will come together with the next kosmos release).

https://github.com/jakibaki/sys-netcheat/commit/9476b84de06f591730698190992e36420f4bbc3a

**Comment by shoedrip** [comment]
Excuse me, but, what are PM modules? I see no such thing documented on atmosphere's git. I managed to build sys-netcheat but since it's not a kip anymore, I don't know how I should load it.
