### ISSUE TITLE
Typo in LuaHelper

### ISSUE THREAD

**Issue by ckurtz22** [jakibaki/sys-netcheat#8]
Was having issues getting `getResultsLength` to work earlier, then when looking through the source, I noticed on line 264 of luahelper.c there was a typo
`static int luaGetResultsLenght(lua_State *L)` 
The word `length` is misspelled which is what was preventing me from using it properly earlier.

**Comment by jakibaki** [comment]
Oops, thanks! I'll push a fix in a few minutes!
